# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"\x1e\n\x0eMessageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"+\n\x0fMessageResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x02 \x01(\tB\x14\n\x12\x63om.epam.mentoringb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022com.epam.mentoring'
  _MESSAGEREQUEST._serialized_start=18
  _MESSAGEREQUEST._serialized_end=48
  _MESSAGERESPONSE._serialized_start=50
  _MESSAGERESPONSE._serialized_end=93
# @@protoc_insertion_point(module_scope)
