grpc:
  client:
    local-grpc-message-server:
      address: 'static://127.0.0.1:8080'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

server:
  port: 8081
