spring:
  cloud:
    function:
      definition: carConsumer
    stream:
      bindings:
        carConsumer-in-0:
          destination: vehicle-details
          contentType: application/*+avro
      kafka:
        bindings:
          carConsumer-in-0:
            consumer:
              configuration:
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                specific.avro.reader: true
                schema.registry.url: http://localhost:8081

server:
  port: 8101
